### ISSUE TITLE
Koko running on Linux

### ISSUE THREAD

**Issue by injectless** [noraesae/koko#24]
Hi everyone,

I'm trying to start the app in Ubuntu 16.04, after running npm install

 ```

awk@awk:~/Documents/koko-master$ npm start
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

```

And the following file (npm-debug.log) would be:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /home/awk/Documents/koko-master
6 error Linux 4.4.0-22-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 error node v4.2.6
9 error npm  v3.5.2
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

```

Does anyone have a clue how can I get this running on Ubuntu?
Thanks.

**Comment by egladman** [comment]
i'm running it fine on arch linux. run `npm install && make run`

**Comment by injectless** [comment]
Running, but not running so good though.
 I'm sure is just me.. it connects, but to switch between channels, or embed video like the screenshot, or someother features seems to be missing.

**Comment by mmarkman** [comment]
is this a copy of [#3](https://github.com/noraesae/koko/issues/3)?

**Comment by fppaess** [comment]
@matikbird I packed a deb_x64 version of koko. It's working fine here.
Elementary OS 0.4.1 Loki - based on Ubuntu 16.04 Xenial. I installed it using Eddy.
It would be great if you could test it. [koko_0.2.1_amd64.deb](https://github.com/fppaess/koko/blob/deb-release/koko_0.2.1_amd64.deb)

![screenshot from 2017-07-12 04 34 14](https://user-images.githubusercontent.com/12243928/28107626-ea3f776e-66be-11e7-9b65-683e753601f1.png)

**Comment by timypcr** [comment]
@fppaess the link to your .deb package is broken, could you share it again and I'll test it on Ubuntu 16.04.
